# Generated by Django 3.1.5 on 2021-01-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210122_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='profile_pic',
            new_name='profilePic',
        ),
    ]
