# Generated by Django 3.1.5 on 2021-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210122_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
