# Generated by Django 3.1.5 on 2021-01-22 15:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210122_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='profilePic',
            field=stdimage.models.StdImageField(upload_to='Images/'),
        ),
    ]
